import React, { useState } from 'react';
import { WHATSAPP_NUMBER } from './constants';

const screens = [
  { name: 'Billing', title: 'Follow a sale through checkout.', copy: 'See how items appear on a bill, review the total, and understand the receipt workflow during your demo.', image: '/urthly-pos-interface-preview.png', alt: 'Urthly POS billing screen with green navigation and product search', visualClass: 'interface-preview', caption: 'Urthly POS billing interface.' },
  { name: 'Inventory', title: 'See how your stock is organised.', copy: 'Review the product list and stock information with the team. Bring your inventory questions to the demo.', image: '/urthly-inventory-preview.png', alt: 'Urthly POS stock report with inventory quantities and reorder status', visualClass: 'inventory-preview', caption: 'Urthly POS inventory and stock report.' },
  { name: 'Reporting', title: 'Review the day’s sales.', copy: 'Explore the available sales reports and confirm which views help you review your business.', image: '/urthly-reports-dashboard-clean.png', alt: 'Urthly POS reporting dashboard with sales and expense summaries', visualClass: 'dashboard-preview', caption: 'Urthly POS reporting dashboard.' },
];

export default function Homepage() {
  const [business, setBusiness] = useState('Retail or supermarket');
  const [message, setMessage] = useState('');
  const [activeScreen, setActiveScreen] = useState(0);
  const screen = screens[activeScreen];
  const moveScreen = (event: React.KeyboardEvent<HTMLButtonElement>, index: number) => {
    const last = screens.length - 1;
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? last : event.key === 'ArrowRight' ? (index + 1) % screens.length : event.key === 'ArrowLeft' ? (index + last) % screens.length : null;
    if (next === null) return;
    event.preventDefault(); setActiveScreen(next); document.getElementById(`tab-${next}`)?.focus();
  };
  const prepareMessage = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    setMessage(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(`Hello Urthly POS, I would like a demo.\nName: ${data.get('name')}\nBusiness: ${business}\nLocation: ${data.get('location')}`)}`);
  };

  return <>
    <a className="skip-link" href="#product">Skip to content</a>
    <header className="header"><nav className="wrap nav" aria-label="Main navigation"><a className="brand" href="#top"><img src="/logo.png" alt="" />urthly<span>POS</span></a><div className="links"><a href="#product">Product</a><a href="#industries">Business types</a><a href="#setup">Hardware &amp; setup</a><a href="#pricing">Pricing</a></div><a className="button" href="#demo">Book a demo <span aria-hidden="true">↗</span></a></nav></header>
    <main aria-label="Business and purchase information">
      <section className="hero wrap" id="top"><div className="hero-grid"><div><p className="eyebrow">Urthly point of sale</p><h1>POS software for Sri Lankan shops.</h1><p className="intro">Manage billing, stock, and daily sales with Urthly POS.</p><div className="actions"><a className="button" href="#demo">Book a demo <span aria-hidden="true">↗</span></a><a className="text-link" href="#pricing">View pricing</a></div><p className="context">See the software. Discuss your store’s setup.</p></div><figure className="product-figure"><div className="asset hero-asset interface-preview"><img src="/urthly-pos-interface-preview.png" alt="Urthly POS billing screen with green navigation and product search" width="1680" height="943" /></div><figcaption className="caption">Urthly POS billing interface.</figcaption></figure></div><div className="overview"><div><strong>At the counter</strong><p>Billing and receipts.</p></div><div><strong>Behind the counter</strong><p>Products and stock.</p></div><div><strong>At the end of the day</strong><p>Sales and reporting.</p></div></div></section>
      <section className="product wrap" id="product"><div className="section-heading"><div><p className="eyebrow">Inside the software</p><h2>A closer look at your daily work.</h2></div><p>Explore the screens your team would use, from a sale to the day’s totals.</p></div><div className="tabs" role="tablist" aria-label="Product screens">{screens.map((item, index) => <button id={`tab-${index}`} key={item.name} type="button" role="tab" aria-selected={activeScreen === index} aria-controls="product-panel" tabIndex={activeScreen === index ? 0 : -1} onClick={() => setActiveScreen(index)} onKeyDown={(event) => moveScreen(event, index)}>{item.name}</button>)}</div><div className="panel" role="tabpanel" id="product-panel" aria-labelledby={`tab-${activeScreen}`}><figure className="product-figure"><div className={`asset product-asset ${screen.visualClass}`}><img src={screen.image} alt={screen.alt} width="1680" height="943" /></div><figcaption className="caption">{screen.caption}</figcaption></figure><div className="panel-copy"><p className="index">0{activeScreen + 1} / {screen.name.toUpperCase()}</p><h3>{screen.title}</h3><p>{screen.copy}</p><a className="text-link" href="#demo">See it in a demo ↗</a></div></div></section>
      <section className="section-band" id="industries"><div className="wrap section-space"><div className="section-heading"><div><p className="eyebrow">Your business</p><h2>Start with your store’s requirements.</h2></div><p>Choose your business type to include it in your demo request.</p></div><div className="business-list">{[['Retail or supermarket','Retail & supermarkets','Discuss barcode billing, product units, stock levels, and cashier access.'],['Pharmacy','Pharmacies','Walk through your requirements for medicine lookup, batches, expiry dates, and receipts.'],['Restaurant or café','Restaurants & cafés','Discuss ordering, kitchen tickets, tables, and how customers settle a bill.']].map(([value,title,copy],index)=><article key={value}><span className="row-number">0{index+1}</span><div><h3>{title}</h3><p>{copy}</p></div><a className="text-link" href="#demo" onClick={()=>{setBusiness(value);setMessage('');}}>Discuss my business ↗</a></article>)}</div></div></section>
      <section className="wrap section-space" id="setup"><div className="section-heading"><div><p className="eyebrow">Hardware & installation</p><h2>Plan the whole counter.</h2></div><p>Share what you already use so the discussion starts with your equipment.</p></div><div className="setup-grid"><div className="equipment"><h3>Bring your equipment details.</h3><dl>{[['Computer','Model and operating system'],['Receipt printer','Model, paper size, and connection'],['Barcode scanner','Model and connection type'],['Other equipment','Cash drawer, scale, or extra display']].map(([title,copy])=><div key={title}><dt>{title}</dt><dd>{copy}</dd></div>)}</dl><p>Compatibility is confirmed for your specific setup.</p></div><ol className="setup-steps">{[['Review your workflow','Explain your counters, products, staff, and busiest periods.'],['Prepare the setup','Confirm equipment, data preparation, migration work, and costs.'],['Agree the handover','Set expectations for installation, cashier training, and ongoing support.']].map(([title,copy])=><li key={title}><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>
      <section className="section-band" id="pricing"><div className="wrap section-space pricing-layout"><div><p className="eyebrow">Pricing</p><h2>Get a clear price for your setup.</h2><p className="section-copy">Your counter count, equipment, and setup requirements belong in one written estimate.</p><a className="button" href="#demo">Request an estimate ↗</a></div><div className="quote-detail"><h3>What to confirm in your quote</h3><dl>{[['Software','License scope and number of counters'],['Equipment','Hardware to reuse or purchase'],['Getting started','Installation, migration, and training'],['After installation','Support, updates, and optional services']].map(([title,copy])=><div key={title}><dt>{title}</dt><dd>{copy}</dd></div>)}</dl><p>Ask for one-time costs and recurring charges to be listed separately.</p></div></div></section>
      <section className="wrap section-space faq-layout" id="faq"><div><p className="eyebrow">Before you decide</p><h2>A few practical questions.</h2></div><div className="faq-list">{[['Can I use my existing equipment?','Share the models of your computer, receipt printer, and scanner. The team can review compatibility and identify any equipment needed.'],['Can I bring my current product list?','Bring a sample of your data to the demo. Discuss the file format, preparation, and any migration work needed.'],['What should I confirm about offline use?','Ask for a demonstration of billing without internet and clarification of connectivity requirements for backups, updates, and optional services.'],['What does the price include?','Request a written estimate covering the license, counters, hardware, installation, training, migration, and ongoing support. Confirm recurring charges before purchase.'],['How do I arrange a demo?','Use the form below to prepare a WhatsApp message. Review and send it in WhatsApp; the team will arrange a time with you.']].map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="contact-section" id="demo"><div className="wrap section-space contact-layout"><div><p className="eyebrow">Talk to Urthly</p><h2>Let’s look at your store.</h2><p className="section-copy">Tell us what you sell and where you operate. Use the demo to ask about your workflow, equipment, and setup.</p><a className="contact-phone" href={`tel:+${WHATSAPP_NUMBER}`}>+94 77 536 4754</a><p className="context">Prefer a call? Speak with the team directly.</p></div><form className="contact-form" onChange={()=>setMessage('')} onSubmit={prepareMessage}><h3>Request a demo</h3><label htmlFor="name">Your name<input id="name" name="name" autoComplete="name" required maxLength={100}/></label><label htmlFor="business">Business type<select id="business" value={business} onChange={event=>setBusiness(event.target.value)}>{['Retail or supermarket','Pharmacy','Restaurant or café','Other'].map(value=><option key={value}>{value}</option>)}</select></label><label htmlFor="location">Store location<input id="location" name="location" autoComplete="address-level2" required maxLength={150} placeholder="Town or city"/></label><p className="form-note">Prepare a message, then review and send it in WhatsApp. Your request is sent only when you send that message.</p><button className="button" type="submit">Prepare WhatsApp message ↗</button>{message&&<div className="message-ready" role="status"><p>Your message is ready.</p><a className="text-link" href={message} target="_blank" rel="noopener noreferrer">Open WhatsApp to review and send ↗</a></div>}</form></div></section>
    </main>
    <footer className="footer wrap"><div><a className="brand" href="#top">urthly<span>POS</span></a><p>Point-of-sale software for Sri Lankan businesses.</p></div><nav aria-label="Footer navigation"><a href="#product">Product</a><a href="#pricing">Pricing</a><a href="#faq">FAQs</a><a href="#demo">Contact</a></nav><small>© {new Date().getFullYear()} Urthly POS</small></footer>
  </>;
}
