import React, { useEffect, useRef, useState } from 'react';
import { WHATSAPP_NUMBER } from './constants';

type EnquiryIntent = 'demo' | 'quote';
const salesWhatsapp = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent('Hello Urthly POS, I have a sales enquiry.')}`;

const screens = [
  { name: 'Billing', title: 'Complete everyday sales at the counter.', copy: 'Find products by search or barcode, review the current sale and total, then use the receipt controls.', image: '/urthly-pos-interface-preview.png', alt: 'Urthly POS billing screen showing product search, the current sale and receipt controls', visualClass: 'interface-preview', caption: 'Billing screen with product search, the current sale and receipt controls.', callouts: ['Product and barcode search', 'Current sale', 'Sale total and receipt controls'] },
  { name: 'Inventory', title: 'Keep current stock easy to review.', copy: 'Search the product list, review current quantities and identify low-stock information from the stock report.', image: '/urthly-inventory-preview.png', alt: 'Urthly POS stock report showing product search, stock quantities and reorder status', visualClass: 'inventory-preview', caption: 'Inventory report with product search, current quantities and low-stock status.', callouts: ['Product search', 'Current stock quantities', 'Low-stock information'] },
  { name: 'Reporting', title: 'Review sales, profit and expenses.', copy: 'Use the reporting dashboard to review sales totals, profit information and expense information.', image: '/urthly-reports-dashboard-clean.png', alt: 'Urthly POS reporting dashboard showing sales, profit and expense summaries', visualClass: 'dashboard-preview', caption: 'Reporting dashboard with sales, profit and expense information.', callouts: ['Sales totals', 'Profit information', 'Expense information'] },
];

const businessTypes = [
  { value: 'Retail / Supermarket', title: 'Retail shops & supermarkets', standard: ['Barcode billing', 'Product variants and units', 'Stock management', 'Cashier permissions', 'Returns', 'Reporting'], optional: ['Multiple counters', 'Multiple branches'], cta: 'Request a Retail Demo' },
  { value: 'Pharmacy', title: 'Pharmacies', standard: ['Normal POS functions', 'Stock management', 'Expiry-date tracking', 'Returns'], optional: ['Medicine lookup', 'Batch tracking', 'Expiry alerts', 'NMRA-related functionality', 'Multiple counters', 'Multiple branches'], cta: 'Request a Pharmacy Demo' },
  { value: 'Restaurant / Café', title: 'Restaurants & cafés', standard: ['Table management', 'Dine-in', 'Takeaway', 'KOT / kitchen tickets', 'Receipt printing'], optional: ['Split billing', 'Order modifiers', 'Ingredient inventory', 'Multiple counters', 'Multiple branches'], cta: 'Request a Restaurant Demo' },
];

const faqs = [
  ['Does Urthly POS work without internet?', 'Yes. Normal day-to-day billing, barcode scanning, receipt printing, inventory, returns and refunds, reports, and staff accounts work offline. Internet is required for licence activation, software updates and remote technical support. A normal single-store setup does not need to synchronise when connectivity returns.'],
  ['How much does Urthly POS cost?', 'The software costs LKR 75,000 as a one-time payment. The complete POS package costs LKR 160,000. Prices shown are final. Multiple counters, multiple branches, optional industry functions and special configurations require a written quotation.'],
  ['Is the licence lifetime?', 'Yes. The LKR 75,000 software price includes a lifetime licence with no monthly software subscription. First-year technical support and software updates are included.'],
  ['What is included in the LKR 160,000 package?', 'The complete package includes the software, a desktop computer, an XP-80T 80mm receipt printer, a USB barcode scanner, a cash drawer, installation, initial setup, initial staff training, and the first year of support and updates. A UPS is not included.'],
  ['Can I use my existing hardware?', 'Yes, when it is compatible. Urthly checks your existing equipment before installation. The XP-80T 80mm receipt printer, standard USB barcode scanners and a cash drawer are supported. Other receipt printers must be checked rather than assumed compatible.'],
  ['Which Windows versions are supported?', 'Urthly POS supports Windows 10 and Windows 11. The minimum PC specification is an Intel Core i3 processor, 8 GB RAM and a 128 GB SSD.'],
  ['How long does installation take?', 'A normal installation typically takes approximately half a day. Complex migrations or special configurations are assessed case by case.'],
  ['Can installation be completed remotely?', 'Yes. Remote installation is available anywhere in Sri Lanka. On-site installation depends on the customer’s location.'],
  ['Is staff training included?', 'Yes. Initial training for relevant staff is included. The format depends on the installation method and the duration depends on the business and setup. Additional or repeat training is paid.'],
  ['Is technical support included?', 'Technical support and software updates are included for the first year. Continued support and updates after the first year cost LKR 15,000 per year. If the plan is not renewed, the lifetime licence continues to work, but technical support and new updates are no longer included.'],
  ['Is WhatsApp used for technical support?', 'No. Technical support is provided by phone, remote desktop, and on-site service depending on location. WhatsApp is available for sales enquiries.'],
  ['Can multiple counters be supported?', 'Yes, as an optional setup. Urthly will assess the required configuration and provide a written quotation.'],
  ['Can multiple branches be supported?', 'Yes, as an optional setup. The required configuration is assessed and quoted separately.'],
  ['Does Urthly POS support pharmacies?', 'The standard pharmacy setup includes normal POS functions, stock management, expiry-date tracking and returns. Medicine lookup, batch tracking, expiry alerts, NMRA-related functionality, multiple counters and multiple branches are optional additions.'],
  ['Does Urthly POS support restaurants and cafés?', 'The standard restaurant and café setup supports table management, dine-in, takeaway, KOT or kitchen tickets, and receipt printing. Split billing, order modifiers, ingredient inventory, multiple counters and multiple branches are optional additions.'],
  ['How are backups handled?', 'A backup is created automatically when the system exits and is stored on the same PC by default. An external backup is strongly recommended. Recovery is possible when a usable external backup exists, but may not be possible if the only copy was on a failed computer. Cloud backup is not included as standard.'],
  ['Is the demo free?', 'Yes. Use the form below to prepare a free demo request in WhatsApp. Nothing is sent until you review and send the message yourself.'],
  ['What happens after I request a demo?', 'The Urthly team normally responds within one hour to arrange the demo. The demo covers the software and your business requirements. A written quotation can then be prepared and is valid for 30 days.'],
];

export default function Homepage() {
  const [business, setBusiness] = useState('Retail / Supermarket');
  const [intent, setIntent] = useState<EnquiryIntent>('demo');
  const [message, setMessage] = useState('');
  const [activeScreen, setActiveScreen] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const menuButtonRef = useRef<HTMLButtonElement>(null);
  const firstMenuLinkRef = useRef<HTMLAnchorElement>(null);
  const screen = screens[activeScreen];

  useEffect(() => { if (menuOpen) firstMenuLinkRef.current?.focus(); }, [menuOpen]);
  useEffect(() => {
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && menuOpen) { setMenuOpen(false); menuButtonRef.current?.focus(); }
    };
    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  }, [menuOpen]);

  const moveScreen = (event: React.KeyboardEvent<HTMLButtonElement>, index: number) => {
    const last = screens.length - 1;
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? last : event.key === 'ArrowRight' ? (index + 1) % screens.length : event.key === 'ArrowLeft' ? (index + last) % screens.length : null;
    if (next === null) return;
    event.preventDefault(); setActiveScreen(next); document.getElementById(`tab-${next}`)?.focus();
  };
  const chooseEnquiry = (nextIntent: EnquiryIntent, nextBusiness?: string) => { setIntent(nextIntent); if (nextBusiness) setBusiness(nextBusiness); setMessage(''); };
  const prepareMessage = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget); const request = intent === 'demo' ? 'a free demo' : 'a written quotation';
    setMessage(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(`Hello Urthly POS, I would like ${request}.\nName: ${data.get('name')}\nBusiness: ${business}\nLocation: ${data.get('location')}`)}`);
  };
  const closeMenu = () => setMenuOpen(false);

  return <>
    <a className="skip-link" href="#main-content">Skip to content</a>
    <header className="header"><nav className="wrap nav" aria-label="Main navigation"><a className="brand" href="#top" aria-label="Urthly POS home"><img src="/logo.png" alt="" />urthly<span>POS</span></a><div className="links"><a href="#product">Product</a><a href="#industries">Business Types</a><a href="#setup">Setup &amp; Support</a><a href="#pricing">Pricing</a><a href="#faq">FAQs</a></div><a className="button nav-cta" href="#enquiry" onClick={() => chooseEnquiry('demo')}>Request a Demo</a><button ref={menuButtonRef} className="menu-button" type="button" aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={() => setMenuOpen(open => !open)}><span aria-hidden="true">{menuOpen ? '×' : '☰'}</span><span className="sr-only">{menuOpen ? 'Close' : 'Open'} navigation</span></button></nav>{menuOpen && <nav className="mobile-menu" id="mobile-menu" aria-label="Mobile navigation"><a ref={firstMenuLinkRef} href="#product" onClick={closeMenu}>Product</a><a href="#industries" onClick={closeMenu}>Business Types</a><a href="#setup" onClick={closeMenu}>Setup &amp; Support</a><a href="#pricing" onClick={closeMenu}>Pricing</a><a href="#faq" onClick={closeMenu}>FAQs</a><a className="button" href="#enquiry" onClick={() => { chooseEnquiry('demo'); closeMenu(); }}>Request a Demo</a></nav>}</header>
    <main id="main-content" aria-label="Business and purchase information">
      <section className="hero wrap" id="top"><div className="hero-grid"><div><p className="eyebrow">Urthly point of sale</p><h1>POS software for Sri Lankan shops.</h1><p className="intro">Manage billing, stock, and daily sales with Urthly POS.</p><div className="actions"><a className="button" href="#enquiry" onClick={() => chooseEnquiry('demo')}>Request a Free Demo</a><a className="text-link" href="#pricing">View Pricing</a></div><ul className="hero-assurances" aria-label="Purchase reassurance"><li>Lifetime licence</li><li>No monthly software subscription</li><li>Installation &amp; initial staff training included</li></ul></div><figure className="product-figure"><div className="asset hero-asset interface-preview"><img src="/urthly-pos-interface-preview.png" alt="Urthly POS billing screen showing product search and a current sale" width="1680" height="943" /></div><figcaption className="caption">Actual Urthly POS billing interface.</figcaption></figure></div></section>
      <section className="reassurance-band" aria-label="Urthly POS reassurance"><div className="wrap reassurance-grid"><div><strong>Works Offline</strong><p>Normal day-to-day operations work without internet.</p></div><div><strong>Setup Included</strong><p>Installation, initial setup and initial training are included.</p></div><div><strong>Lifetime Licence</strong><p>One-time software payment with no monthly subscription.</p></div><div><strong>First-Year Support</strong><p>Technical support and software updates are included.</p></div></div></section>
      <section className="wrap core-value" aria-labelledby="core-value-title"><div className="section-heading"><div><p className="eyebrow">Your working day</p><h2 id="core-value-title">The essentials, from opening to close.</h2></div><p>Urthly POS keeps the core counter, stock and reporting work together.</p></div><div className="value-grid"><div><strong>At the Counter</strong><p>Bill customers, scan barcodes, print receipts and handle returns.</p></div><div><strong>Behind the Counter</strong><p>Manage products, stock, staff accounts and cashier permissions.</p></div><div><strong>At the End of the Day</strong><p>Review sales, profit, expenses and stock reports.</p></div></div></section>
      <section className="product wrap" id="product"><div className="section-heading"><div><p className="eyebrow">Inside the software</p><h2>A closer look at your daily work.</h2></div><p>Use the tabs to see the actual Billing, Inventory and Reporting screens.</p></div><div className="tabs" role="tablist" aria-label="Product screens">{screens.map((item, index) => <button id={`tab-${index}`} key={item.name} type="button" role="tab" aria-selected={activeScreen === index} aria-controls="product-panel" tabIndex={activeScreen === index ? 0 : -1} onClick={() => setActiveScreen(index)} onKeyDown={(event) => moveScreen(event, index)}>{item.name}</button>)}</div><div className="panel" role="tabpanel" id="product-panel" aria-labelledby={`tab-${activeScreen}`}><figure className="product-figure"><div className={`asset product-asset ${screen.visualClass}`}><img src={screen.image} alt={screen.alt} width="1680" height="943" /></div><figcaption className="caption">{screen.caption}</figcaption></figure><div className="panel-copy"><p className="index">0{activeScreen + 1} / {screen.name.toUpperCase()}</p><h3>{screen.title}</h3><p>{screen.copy}</p><ul className="screen-callouts">{screen.callouts.map(item => <li key={item}>{item}</li>)}</ul><a className="text-link" href="#enquiry" onClick={() => chooseEnquiry('demo')}>Request a Demo</a></div></div></section>
      <section className="section-band" id="industries"><div className="wrap section-space"><div className="section-heading"><div><p className="eyebrow">Your business</p><h2>Choose the setup that fits your work.</h2></div><p>Standard functions are included in the relevant setup. Optional functions are assessed and quoted separately.</p></div><div className="business-list">{businessTypes.map((item, index) => <article key={item.value}><span className="row-number">0{index + 1}</span><div><h3>{item.title}</h3><div className="feature-groups"><div><strong>Standard support</strong><p>{item.standard.join(' · ')}</p></div><div><strong>Optional setup</strong><p>{item.optional.join(' · ')}</p></div></div></div><a className="text-link" href="#enquiry" onClick={() => chooseEnquiry('demo', item.value)}>{item.cta}</a></article>)}</div></div></section>
      <section className="wrap section-space operations" id="offline"><div className="section-heading"><div><p className="eyebrow">Offline operation &amp; data</p><h2>Keep working when the internet is unavailable.</h2></div><p>Internet is needed for activation, updates and remote support—not for normal daily work.</p></div><div className="operations-grid"><article><h3>What works offline</h3><ul className="check-list"><li>Billing and barcode scanning</li><li>Receipt printing</li><li>Inventory</li><li>Returns and refunds</li><li>Reports</li><li>Staff accounts</li></ul><p>A normal single-store setup does not need to synchronise when connectivity returns.</p></article><article><h3>Backup and recovery</h3><p>A backup is created automatically when the system exits. By default, it is stored on the same PC.</p><p><strong>Keep an external backup.</strong> Recovery is possible when a usable external copy exists. It may not be possible if the only copy was stored on a failed computer.</p><p>Cloud backup is not included as standard.</p></article></div></section>
      <section className="section-band" id="setup"><div className="wrap section-space"><div className="section-heading"><div><p className="eyebrow">Setup &amp; support</p><h2>Know what you need and what Urthly provides.</h2></div><p>The Urthly team checks compatibility before installation and helps prepare the complete counter.</p></div><div className="setup-grid"><article className="information-block"><h3>Hardware</h3><dl><div><dt>Minimum PC</dt><dd>Windows 10 or 11, Intel Core i3, 8 GB RAM, 128 GB SSD</dd></div><div><dt>Receipt printer</dt><dd>XP-80T, 80mm</dd></div><div><dt>Supported</dt><dd>Standard USB barcode scanner and cash drawer</dd></div><div><dt>Optional</dt><dd>Weighing scale and customer display</dd></div><div><dt>Power protection</dt><dd>UPS recommended; not required</dd></div></dl><p>You can use existing compatible equipment. Other receipt printers must be checked before installation.</p></article><article className="information-block"><h3>Installation</h3><p>A normal installation typically takes approximately half a day. Remote installation is available anywhere in Sri Lanka; on-site installation depends on location.</p><ul className="check-list"><li>Software installation and licence activation</li><li>Printer, scanner and cash-drawer setup</li><li>Normal product import</li><li>User, business and invoice configuration</li><li>Billing tests and initial staff training</li></ul><p>Complex migrations and special configurations are assessed case by case.</p></article><article className="information-block"><h3>Initial training</h3><p>Initial training for relevant staff is included. Its format follows the installation method, and its duration depends on the business and setup.</p><p>Training covers billing, barcode use, stock, returns and refunds, reports, user management, backup and basic troubleshooting.</p><p>Additional or repeat training is paid.</p></article><article className="information-block"><h3>Technical support</h3><p>The first year of technical support and software updates is included.</p><p>Support is available by phone and remote desktop across Sri Lanka during business hours. On-site support depends on location, and urgent support is handled case by case.</p><p><strong>After year one: LKR 15,000 per year</strong> for continued technical support and updates. Without renewal, the lifetime licence keeps working, but support and new updates are not included.</p></article></div></div></section>
      <section className="wrap section-space" id="pricing"><div className="section-heading"><div><p className="eyebrow">Clear pricing</p><h2>Choose software or a complete counter package.</h2></div><p>Both options include a lifetime software licence with no monthly software subscription.</p></div><div className="pricing-grid"><article className="price-card"><p className="price-label">Urthly POS software</p><p className="price">LKR 75,000</p><p className="price-basis">One-time payment · Lifetime licence</p><h3>Included</h3><ul className="check-list"><li>Urthly POS software</li><li>Installation and initial setup</li><li>Initial staff training</li><li>Normal product import</li><li>First year of technical support</li><li>First year of software updates</li></ul><a className="button" href="#enquiry" onClick={() => chooseEnquiry('quote')}>Get a Written Quote</a></article><article className="price-card featured"><p className="price-label">Complete POS package</p><p className="price">LKR 160,000</p><p className="price-basis">Software and counter hardware</p><h3>Everything in the software option, plus</h3><ul className="check-list"><li>Desktop computer</li><li>XP-80T 80mm receipt printer</li><li>USB barcode scanner</li><li>Cash drawer</li></ul><p className="exclusion"><strong>UPS is not included.</strong></p><a className="button" href="#enquiry" onClick={() => chooseEnquiry('quote')}>Get a Written Quote</a></article></div><div className="pricing-notes"><div><strong>Optional or custom quotation</strong><p>Multiple counters, multiple branches, some industry-specific functions, weighing scales, customer displays and special configurations.</p></div><div><strong>Support after year one</strong><p>LKR 15,000 per year for continued technical support and software updates.</p></div><div><strong>Written quotations</strong><p>Prices shown are final. Written quotations are valid for 30 days.</p></div></div></section>
      <section className="company-section" id="about"><div className="wrap section-space company-layout"><div><p className="eyebrow">About Urthly</p><h2>A Sri Lankan POS team serving businesses nationwide.</h2><p className="section-copy">Urthly POS is operated by Urthly (Pvt) Ltd. The Urthly team has operated since 2021 and provides remote installation and support across Sri Lanka.</p></div><address><strong>Urthly (Pvt) Ltd</strong><span>133/5, Welihena Road</span><span>Kochchikade, Sri Lanka</span><a href="tel:+94775364754">+94 77 536 4754</a><a href={salesWhatsapp} target="_blank" rel="noopener noreferrer">WhatsApp Urthly for sales</a><a href="mailto:urthly25@gmail.com">urthly25@gmail.com</a></address></div></section>
      <section className="wrap section-space faq-layout" id="faq"><div><p className="eyebrow">Before you decide</p><h2>Direct answers to practical questions.</h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="contact-section" id="enquiry"><div className="wrap section-space contact-layout"><div><p className="eyebrow">Talk to Urthly</p><h2>{intent === 'demo' ? 'See Urthly POS for your business.' : 'Get a written price for your setup.'}</h2><p className="section-copy">{intent === 'demo' ? 'The free demo covers the software and your business requirements.' : 'The Urthly team will confirm your software, hardware and optional setup requirements before preparing the quotation.'}</p><p>Typical enquiry response: <strong>within 1 hour</strong>.</p><a className="contact-phone" href="tel:+94775364754">Call +94 77 536 4754</a><p className="context">WhatsApp is available for sales enquiries. Technical support is provided separately by phone, remote desktop or on-site depending on location.</p></div><form className="contact-form" onChange={() => setMessage('')} onSubmit={prepareMessage}><fieldset className="intent-switch"><legend>What would you like?</legend><button type="button" aria-pressed={intent === 'demo'} onClick={() => chooseEnquiry('demo')}>Request a Demo</button><button type="button" aria-pressed={intent === 'quote'} onClick={() => chooseEnquiry('quote')}>Get a Written Quote</button></fieldset><h3>{intent === 'demo' ? 'Request a Free Demo' : 'Request a Written Quote'}</h3><label htmlFor="name">Your name <span aria-hidden="true">*</span><input id="name" name="name" autoComplete="name" required maxLength={100} /></label><label htmlFor="business">Business type <span aria-hidden="true">*</span><select id="business" name="business" required value={business} onChange={event => setBusiness(event.target.value)}>{['Retail / Supermarket', 'Pharmacy', 'Restaurant / Café', 'Other'].map(value => <option key={value}>{value}</option>)}</select></label><label htmlFor="location">Store location <span aria-hidden="true">*</span><input id="location" name="location" autoComplete="address-level2" required maxLength={150} placeholder="Town or city" /></label><p className="form-note">The website prepares a WhatsApp message using these details. Nothing is sent automatically. You must open WhatsApp, review the message and tap Send yourself.</p><button className="button" type="submit">Prepare WhatsApp Message</button>{message && <div className="message-ready" role="status"><p>Your message is ready.</p><a className="text-link" href={message} target="_blank" rel="noopener noreferrer">Open WhatsApp to review and send</a></div>}</form></div><div className="wrap privacy-note" id="privacy"><strong>Privacy</strong><p>Urthly uses enquiry information to respond, understand business requirements, arrange demos, prepare quotations and provide related sales communication. Urthly does not share enquiry information with third parties. For deletion or privacy requests, email <a href="mailto:urthly25@gmail.com">urthly25@gmail.com</a>.</p></div></section>
    </main>
    <footer className="footer wrap"><div><a className="brand" href="#top">urthly<span>POS</span></a><p><strong>Urthly (Pvt) Ltd</strong><br />133/5, Welihena Road<br />Kochchikade, Sri Lanka</p><p>Serving businesses across Sri Lanka.</p></div><div className="footer-contact"><a href="tel:+94775364754">+94 77 536 4754</a><a href={salesWhatsapp} target="_blank" rel="noopener noreferrer">WhatsApp sales enquiries</a><a href="mailto:urthly25@gmail.com">urthly25@gmail.com</a></div><nav aria-label="Footer navigation"><a href="#product">Product</a><a href="#industries">Business Types</a><a href="#setup">Setup &amp; Support</a><a href="#pricing">Pricing</a><a href="#faq">FAQs</a><a href="#enquiry" onClick={() => chooseEnquiry('demo')}>Request a Demo</a><a href="#enquiry" onClick={() => chooseEnquiry('quote')}>Get a Written Quote</a><a href="#privacy">Privacy</a></nav><small>© 2026 Urthly (Pvt) Ltd. All rights reserved.</small></footer>
  </>;
}
